server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/quizdb
    username: admin
    password: admin
  liquibase:
    url: jdbc:postgresql://localhost:5432/quizdb
    user: admin
    password: admin
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6389

jwt:
  encoder:
    secret: dJvoYnfoe-238fk3oD+cie#$kfvkdkf8&
    iteration: 8
    keyLength: 256
  secret: dJvoYnfoe-238fk3oD+cie#$kfvkdkf8&
  expirationInMS: 10000000000
  issuer: quizRestApiService
